import { Box, ColorModeScript, type ThemeConfig } from '@chakra-ui/react'

import Providers from './Providers'
import Header from '@/components/Header/Header'

import type { Metadata } from 'next'
import type { PropsWithChildren } from 'react'

import '@/styles/globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const config: ThemeConfig = {
  initialColorMode: 'system',
  useSystemColorMode: true,
}

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="ko">
      <body>
        <ColorModeScript initialColorMode={config.initialColorMode} />
        <Providers>
          <Header />
          <Box
            as="main"
            maxW="700px"
            m="0 auto"
            p={{
              base: '80px 16px',
              md: '80px 24px',
            }}
          >
            {children}
          </Box>
        </Providers>
      </body>
    </html>
  )
}
